version: '2'

services:
  postgres_database:
    container_name: postgres-server
    image: postgres
    restart: always
    volumes:
      - pg_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    command: -p 5432
    healthcheck:
      test: "exit 0"
  pg_admin:
    container_name: pgadmin4-server
    image: dpage/pgadmin4
    restart: always
    depends_on:
      postgres_database:
        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
volumes:
  pg_data:
    driver: local