version: '3.8'
services:
  pg_container:
    container_name: pg_container
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    networks:
      - appNet
    volumes:
      - pgData:/var/lib/postgresql
  rbac:
    container_name: service-rbac
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - pg_container

networks:
  appNet:
volumes:
  pgData:
